export const X_KILOCODE_VERSION = "X-ChadCode-Version"
export const X_KILOCODE_ORGANIZATIONID = "X-ChadCode-OrganizationId"
export const X_KILOCODE_TASKID = "X-ChadCode-TaskId"
export const X_KILOCODE_PROJECTID = "X-ChadCode-ProjectId"
export const X_KILOCODE_EDITORNAME = "X-ChadCode-EditorName"
export const X_KILOCODE_TESTER = "X-KILOCODE-TESTER"
